<?php

# TODO add gettext
return [ // tr14
    'AI' => ['Ambiguous (Alphabetic or Ideographic)', 'Act like AL when the resolved EAW is N; otherwise, act as ID'],
    'AL' => ['Alphabetic', 'Are alphabetic characters or symbols that are used with alphabetic characters'],
    'B2' => ['Break Opportunity Before and After', 'Provide a line break opportunity before and after the character'],
    'BA' => ['Break After', 'Generally provide a line break opportunity after the character'],
    'BB' => ['Break Before', 'Generally provide a line break opportunity before the character'],
    'BK' => ['Mandatory Break', 'Cause a line break (after)'],
    'CB' => ['Contingent Break Opportunity', 'Provide a line break opportunity contingent on additional information'],
    'CJ' => ['Conditional Japanese Starter', 'Treat as NS or ID for strict or normal breaking.'],
    'CL' => ['Close Punctuation', 'Prohibit line breaks before'],
    'CM' => ['Combining Mark', 'Prohibit a line break between the character and the preceding character'],
    'CP' => ['Close Parenthesis', 'Prohibit line breaks before'],
    'CR' => ['Carriage Return', 'Cause a line break (after), except between CR and LF'],
    'EB' => ['Emoji Base', 'Do not break from following Emoji Modifier'],
    'EM' => ['Emoji Modifier', 'Do not break from preceding Emoji Base'],
    'EX' => ['Exclamation/Interrogation', 'Prohibit line breaks before'],
    'GL' => ['Non-breaking (“Glue”)', 'Prohibit line breaks before and after'],
    'H2' => ['Hangul LV Syllable', 'Form Korean syllable blocks'],
    'H3' => ['Hangul LVT Syllable', 'Form Korean syllable blocks'],
    'HL' => ['Hebrew Letter', 'Do not break around a following hyphen; otherwise act as Alphabetic'],
    'HY' => ['Hyphen', 'Provide a line break opportunity after the character, except in numeric context'],
    'ID' => ['Ideographic', 'Break before or after, except in some numeric context'],
    'IN' => ['Inseparable', 'Allow only indirect line breaks between pairs'],
    'IS' => ['Infix Numeric Separator', 'Prevent breaks after any and before numeric'],
    'JL' => ['Hangul L Jamo', 'Form Korean syllable blocks'],
    'JT' => ['Hangul T Jamo', 'Form Korean syllable blocks'],
    'JV' => ['Hangul V Jamo', 'Form Korean syllable blocks'],
    'LF' => ['Line Feed', 'Cause a line break (after)'],
    'NL' => ['Next Line', 'Cause a line break (after)'],
    'NS' => ['Nonstarter', 'Allow only indirect line breaks before'],
    'NU' => ['Numeric', 'Form numeric expressions for line breaking purposes'],
    'OP' => ['Open Punctuation', 'Prohibit line breaks after'],
    'PO' => ['Postfix Numeric', 'Do not break following a numeric expression'],
    'PR' => ['Prefix Numeric', 'Do not break in front of a numeric expression'],
    'QU' => ['Quotation', 'Act like they are both opening and closing'],
    'RI' => ['Regional Indicator', 'Keep pairs together. For pairs, break before and after other classes'],
    'SA' => ['Complex Context Dependent (South East Asian)', 'Provide a line break opportunity contingent on additional, language-specific context analysis'],
    'SG' => ['Surrogate', 'Do not occur in well-formed text'],
    'SP' => ['Space', 'Enable indirect line breaks'],
    'SY' => ['Symbols Allowing Break After', 'Prevent a break before, and allow a break after'],
    'WJ' => ['Word Joiner', 'Prohibit line breaks before and after'],
    'XX' => ['Unknown', 'Have as yet unknown line breaking behavior or unassigned code positions'],
    'ZWJ' => ['Zero Width Joiner', 'Prohibit line breaks within joiner sequences'],
    'ZW' => ['Zero Width Space', 'Provide a break opportunity'],
];
