<?php

return [
    'Lu' => __('Uppercase Letter'),
    'Ll' => __('Lowercase Letter'),
    'Lt' => __('Titlecase Letter'),
    'Lm' => __('Modifier Letter'),
    'Lo' => __('Other Letter'),
    'Mn' => __('Nonspacing Mark'),
    'Mc' => __('Spacing Mark'),
    'Me' => __('Enclosing Mark'),
    'Nd' => __('Decimal Number'),
    'Nl' => __('Letter Number'),
    'No' => __('Other Number'),
    'Pc' => __('Connector Punctuation'),
    'Pd' => __('Dash Punctuation'),
    'Ps' => __('Open Punctuation'),
    'Pe' => __('Close Punctuation'),
    'Pi' => __('Initial Punctuation'),
    'Pf' => __('Final Punctuation'),
    'Po' => __('Other Punctuation'),
    'Sm' => __('Math Symbol'),
    'Sc' => __('Currency Symbol'),
    'Sk' => __('Modifier Symbol'),
    'So' => __('Other Symbol'),
    'Zs' => __('Space Separator'),
    'Zl' => __('Line Separator'),
    'Zp' => __('Paragraph Separator'),
    'Cc' => __('Control'),
    'Cf' => __('Format'),
    'Cs' => __('Surrogate'),
    'Co' => __('Private Use'),
    'Cn' => __('Unassigned'),
];
