<?php

return [
    'Africa' => [
        'Ethiopic',
        'Ethiopic Extended',
        'Ethiopic Extended-A',
        'Ethiopic Supplement',
        'NKo',
        'Osmanya',
        'Tifinagh',
        'Meroitic Cursive',
        'Meroitic Hieroglyphs',
        'Bamum',
        'Bamum Supplement',
        'Vai',
        'Adlam',
        'Medefaidrin',
        'Bassa Vah',
        'Mende Kikakui',
    ],
    'America' => [
        'Cherokee',
        'Cherokee Supplement',
        'Deseret',
        'Mayan Numerals',
        'Unified Canadian Aboriginal Syllabics',
        'Unified Canadian Aboriginal Syllabics Extended',
        'Nyiakeng Puachue Hmong',
        'Osage',
    ],
    'Central_Asia' => [
        'Mongolian',
        'Mongolian Supplement',
        'Phags-pa',
        'Tibetan',
        'Chakma',
        'Lepcha',
        'Zanabazar Square',
    ],
    'Philippines' => [
        'Buhid',
        'Hanunoo',
        'Tagalog',
        'Tagbanwa',
        'Batak',
        'Javanese',
        'Rejang',
        'Sundanese',
        'Sundanese Supplement',
    ],
    'Europe' => [
        'Armenian',
        'Basic Latin',
        'Combining Diacritical Marks',
        'Combining Diacritical Marks Supplement',
        'Combining Half Marks',
        'Coptic',
        'Cypriot Syllabary',
        'Cyrillic',
        'Cyrillic Extended-A',
        'Cyrillic Extended-B',
        'Cyrillic Extended-C',
        'Cyrillic Supplement',
        'Georgian',
        'Georgian Supplement',
        'Georgian Extended',
        'Glagolitic',
        'Glagolitic Supplement',
        'Gothic',
        'Greek and Coptic',
        'Greek Extended',
        'IPA Extensions',
        'Latin Extended Additional',
        'Latin Extended-A',
        'Latin Extended-B',
        'Latin Extended-C',
        'Latin Extended-D',
        'Latin Extended-E',
        'Latin-1 Supplement',
        'Linear A',
        'Linear B Ideograms',
        'Linear B Syllabary',
        'Modifier Tone Letters',
        'Ogham',
        'Old Italic',
        'Phonetic Extensions',
        'Phonetic Extensions Supplement',
        'Runic',
        'Shavian',
        'Spacing Modifier Letters',
        'Ancient Greek Musical Notation',
        'Ancient Greek Numbers',
        'Ancient Symbols',
        'Byzantine Musical Symbols',
        'Aegean Numbers',
        'Lycian',
        'Phaistos Disc',
        'Superscripts and Subscripts',
        'General Punctuation',
        'Coptic Epact Numbers',
        'Old Hungarian',
        'Caucasian Albanian',
        'Duployan',
        'Elbasan',
        'Old Permic',
    ],
    'Middle_East' => [
        'Alphabetic Presentation Forms',
        'Arabic',
        'Old South Arabian',
        'Arabic Extended-A',
        'Arabic Mathematical Alphabetic Symbols',
        'Arabic Presentation Forms-A',
        'Arabic Presentation Forms-B',
        'Arabic Supplement',
        'Cuneiform',
        'Hebrew',
        'Old Persian',
        'Phoenician',
        'Syriac',
        'Syriac Supplement',
        'Ugaritic',
        'Samaritan',
        'Egyptian Hieroglyphs',
        'Egyptian Hieroglyph Format Controls',
        'Avestan',
        'Carian',
        'Cuneiform Numbers and Punctuation',
        'Imperial Aramaic',
        'Inscriptional Pahlavi',
        'Inscriptional Parthian',
        'Lydian',
        'Mandaic',
        'Old Turkic',
        'Yezidi',
        'Sogdian',
        'Old Sogdian',
        'Chorasmian',
        'Elymaic',
        'Ottoman Siyaq Numbers',
        'Early Dynastic Cuneiform',
        'Psalter Pahlavi',
        'Palmyrene',
        'Manichaean',
        'Anatolian Hieroglyphs',
        'Hatran',
        'Nabataean',
        'Old North Arabian',
    ],
    'East_Asia' => [
        'Bopomofo',
        'Bopomofo Extended',
        'CJK Symbols and Punctuation',
        'CJK Compatibility',
        'CJK Compatibility Forms',
        'CJK Compatibility Ideographs',
        'CJK Compatibility Ideographs Supplement',
        'CJK Radicals Supplement',
        'CJK Strokes',
        'CJK Unified Ideographs',
        'CJK Unified Ideographs Extension A',
        'CJK Unified Ideographs Extension B',
        'CJK Unified Ideographs Extension C',
        'CJK Unified Ideographs Extension D',
        'CJK Unified Ideographs Extension E',
        'CJK Unified Ideographs Extension F',
        'CJK Unified Ideographs Extension G',
        'Hangul Compatibility Jamo',
        'Hangul Jamo',
        'Hangul Jamo Extended-A',
        'Hangul Jamo Extended-B',
        'Hangul Syllables',
        'Hiragana',
        'Ideographic Description Characters',
        'Kanbun',
        'Kangxi Radicals',
        'Katakana',
        'Katakana Phonetic Extensions',
        'Yi Radicals',
        'Yi Syllables',
        'Yijing Hexagram Symbols',
        'Vertical Forms',
        'Enclosed CJK Letters and Months',
        'Enclosed Ideographic Supplement',
        'Counting Rod Numerals',
        'Kana Supplement',
        'Kana Extended-A',
        'Small Kana Extension',
        'Miao',
        'Halfwidth and Fullwidth Forms',
        'Small Form Variants',
        'Nushu',
        'Marchen',
        'Khitan Small Script',
        'Ideographic Symbols and Punctuation',
        'Soyombo',
        'Tangut',
        'Tangut Components',
        'Tangut Supplement',
        'Pahawh Hmong',
    ],
    'South_Asia' => [
        'Bengali',
        'Devanagari',
        'Devanagari Extended',
        'Common Indic Number Forms',
        'Gujarati',
        'Gurmukhi',
        'Kannada',
        'Kharoshthi',
        'Limbu',
        'Malayalam',
        'Oriya',
        'Sinhala',
        'Syloti Nagri',
        'Tamil',
        'Tamil Supplement',
        'Telugu',
        'Thaana',
        'Brahmi',
        'Meetei Mayek',
        'Meetei Mayek Extensions',
        'Kaithi',
        'Ol Chiki',
        'Saurashtra',
        'Sharada',
        'Sora Sompeng',
        'Vedic Extensions',
        'Takri',
        'Gunjala Gondi',
        'Masaram Gondi',
        'Dives Akuru',
        'Indic Siyaq Numbers',
        'Bhaiksuki',
        'Dogra',
        'Nandinagari',
        'Newa',
        'Wancho',
        'Ahom',
        'Grantha',
        'Khojki',
        'Khudawadi',
        'Mahajani',
        'Modi',
        'Multani',
        'Siddham',
        'Sinhala Archaic Numbers',
        'Tirhuta',
        'Warang Citi',
    ],
    'Southeast_Asia' => [
        'Balinese',
        'Buginese',
        'Khmer',
        'Khmer Symbols',
        'Lao',
        'Myanmar',
        'Myanmar Extended-A',
        'Myanmar Extended-B',
        'New Tai Lue',
        'Tai Le',
        'Tai Tham',
        'Tai Viet',
        'Tai Xuan Jing Symbols',
        'Thai',
        'Cham',
        'Lisu',
        'Lisu Supplement',
        'Kayah Li',
        'Rumi Numeral Symbols',
        'Makasar',
        'Hanifi Rohingya',
        'Mro',
        'Pau Cin Hau',
    ],
    'n' => [
        'Chess Symbols',
        'Symbols and Pictographs Extended-A',
        'Symbols for Legacy Computing',
        'Optical Character Recognition',
        'Transport And Map Symbols',
        'Miscellaneous Symbols',
        'Miscellaneous Technical',
        'Musical Symbols',
        'Miscellaneous Symbols And Pictographs',
        'Miscellaneous Symbols and Arrows',
        'Miscellaneous Mathematical Symbols-A',
        'Miscellaneous Mathematical Symbols-B',
        'Playing Cards',
        'Dingbats',
        'Domino Tiles',
        'Emoticons',
        'Geometric Shapes',
        'Mahjong Tiles',
        'Mathematical Alphanumeric Symbols',
        'Mathematical Operators',
        'Control Pictures',
        'Alchemical Symbols',
        'Arrows',
        'Block Elements',
        'Box Drawing',
        'Currency Symbols',
        'Supplemental Arrows-A',
        'Supplemental Arrows-B',
        'Supplemental Arrows-C',
        'Supplemental Mathematical Operators',
        'Supplemental Punctuation',
        'Supplemental Symbols and Pictographs',
        'Tags',
        'Letterlike Symbols',
        'Variation Selectors',
        'Variation Selectors Supplement',
        'Number Forms',
        'General Punctuation',
        'Combining Diacritical Marks for Symbols',
        'Combining Diacritical Marks Extended',
        'Braille Patterns',
        'Specials',
        'Enclosed Alphanumerics',
        'Enclosed Alphanumeric Supplement',
        'Geometric Shapes Extended',
        'Ornamental Dingbats',
        'Sutton SignWriting',
        'Shorthand Format Controls',
    ],
];
