services:

  web:
    container_name: codepoints-web
    hostname: codepoints.next
    build:
      context: .
      dockerfile: dev/Dockerfile
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./codepoints.net:/var/www/codepoints.net
      - ./config.ini:/var/www/config.ini
      - ./composer.json:/var/www/composer.json
      - ./composer.lock:/var/www/composer.lock
      - ./phpcs.xml:/var/www/phpcs.xml
      - ./psalm.xml:/var/www/psalm.xml
      - ./tests/psalm_stubs.php:/var/www/tests/psalm_stubs.php
      - ./ops/apache2/local-confs/codepoints.net.conf:/etc/apache2/local-confs/codepoints.net.conf
      - ./ops/php/8.3/mods-available/99-codepoints.ini:/usr/local/etc/php/conf.d/99-codepoints.ini
      - ./ops/php/8.3/mods-available/99-develop.ini:/usr/local/etc/php/conf.d/99-develop.ini
      - ./dev/xdebug_output:/tmp/xdebug_output
      - ./dev/popular.json:/var/cache/codepoints/popular.json
    depends_on:
      - db
      - vite
    environment:
      - CODEPTS_LOG_LEVEL=DEBUG
    # https://stackoverflow.com/a/43541681/113195
    extra_hosts:
      - "host.docker.internal:host-gateway"

  db:
    container_name: codepoints-db
    image: mariadb:10.6
    volumes:
      - ./dev/db_data:/var/lib/mysql
      - ./dev/db_init.d:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MARIADB_DATABASE=codepts
      - MARIADB_USER=codepts
      - MARIADB_PASSWORD=codepts

  vite:
    container_name: codepoints-vite
    build:
      context: .
      dockerfile: dev/vite.Dockerfile
    volumes:
      - .:/app

  codeception:
    container_name: codepoints-codeception
    image: codeception/codeception
    volumes:
      - .:/project
    profiles:
      - test
    depends_on:
      - web
