services:

  web:
    container_name: codepoints-web
    build:
      context: .
      dockerfile: dev/Dockerfile
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./codepoints.net:/var/www/html/codepoints.net
      - ./config.ini:/var/www/html/config.ini
      - ./composer.json:/var/www/html/composer.json
      - ./composer.lock:/var/www/html/composer.lock
      - ./phpcs.xml:/var/www/html/phpcs.xml
      - ./psalm.xml:/var/www/html/psalm.xml
      - ./tests/psalm_stubs.php:/var/www/html/tests/psalm_stubs.php
    depends_on:
      - db
      - vite

  db:
    container_name: codepoints-db
    image: mariadb:10.6
    volumes:
      - ./dev/db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MARIADB_DATABASE=codepts
      - MARIADB_USER=codepts
      - MARIADB_PASSWORD=codepts

  vite:
    container_name: codepoints-vite
    build:
      context: .
      dockerfile: dev/vite.Dockerfile
    init: true
    ports:
      - 5173:5173
    volumes:
      - .:/app

  codeception:
    container_name: codepoints-codeception
    image: codeception/codeception
    volumes:
      - .:/project
    profiles:
      - test
