<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <url>
    <loc>http://codepoints.net/</loc>
    <changefreq>yearly</changefreq>
    <priority>0.9</priority>
  </url>
  <url>
    <loc>http://codepoints.net/random</loc>
    <changefreq>always</changefreq>
    <priority>0</priority>
  </url>
  <url>
    <loc>http://codepoints.net/about</loc>
    <changefreq>yearly</changefreq>
    <priority>0.6</priority>
  </url>
  <url>
    <loc>http://codepoints.net/glossary</loc>
    <changefreq>yearly</changefreq>
    <priority>0.6</priority>
  </url>
  <url>
    <loc>http://codepoints.net/scripts</loc>
    <changefreq>yearly</changefreq>
    <priority>0.6</priority>
  </url>
  <url>
    <loc>http://codepoints.net/wizard</loc>
    <changefreq>yearly</changefreq>
    <priority>0.6</priority>
  </url>
  <url>
    <loc>http://codepoints.net/search</loc>
    <changefreq>yearly</changefreq>
    <priority>0.1</priority>
  </url>
  <url>
    <loc>http://codepoints.net/codepoint_of_the_day</loc>
    <changefreq>daily</changefreq>
    <priority>0.6</priority>
  </url>
  <url>
    <loc>http://codepoints.net/codepoint_of_the_day.xml</loc>
    <changefreq>daily</changefreq>
    <priority>0</priority>
  </url>
  <url>
    <loc>http://codepoints.net/planes</loc>
    <changefreq>yearly</changefreq>
    <priority>0.4</priority>
  </url>
  <url>
    <loc>http://codepoints.net/basic_multilingual_plane</loc>
    <changefreq>yearly</changefreq>
  </url>
  <url>
    <loc>http://codepoints.net/supplementary_multilingual_plane</loc>
    <changefreq>yearly</changefreq>
  </url>
  <url>
    <loc>http://codepoints.net/supplementary_ideographic_plane</loc>
    <changefreq>yearly</changefreq>
  </url>
  <url>
    <loc>http://codepoints.net/tertiary_ideographic_plane</loc>
    <changefreq>yearly</changefreq>
  </url>
  <url>
    <loc>http://codepoints.net/supplementary_special-purpose_plane</loc>
    <changefreq>yearly</changefreq>
  </url>
  <url>
    <loc>http://codepoints.net/supplementary_private_use_area_-_a_plane</loc>
    <changefreq>yearly</changefreq>
  </url>
  <url>
    <loc>http://codepoints.net/supplementary_private_use_area_-_b_plane</loc>
    <changefreq>yearly</changefreq>
  </url>
  <url>
    <loc>http://codepoints.net/humans.txt</loc>
    <changefreq>yearly</changefreq>
  </url>
  <url>
    <loc>http://codepoints.net/opensearch.xml</loc>
    <changefreq>yearly</changefreq>
    <priority>0.1</priority>
  </url>
</urlset>
